# Generated by Django 5.2.10 on 2026-01-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantserver', '0003_emails_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumKey',
            fields=[
                ('key_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('key_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_sae', models.CharField(max_length=100)),
                ('target_sae', models.CharField(max_length=100)),
            ],
        ),
    ]
